package com.dhc.dhc_xatrain.daos;

import com.dhc.dhc_xatrain.mapper.Websites;
import java.util.List;

public interface WebsitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated Mon Aug 05 17:41:10 CST 2019
     */
    int insert(Websites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated Mon Aug 05 17:41:10 CST 2019
     */
    List<Websites> selectAll();
}