package com.dhc.dhc_xatrain.mapper;

import java.util.Date;

public class SysLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.id
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.user_id
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.operation
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.ip
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.status
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_time
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.user_id
     *
     * @return the value of sys_login_log.user_id
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.user_id
     *
     * @param userId the value for sys_login_log.user_id
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.operation
     *
     * @return the value of sys_login_log.operation
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.operation
     *
     * @param operation the value for sys_login_log.operation
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.ip
     *
     * @return the value of sys_login_log.ip
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.ip
     *
     * @param ip the value for sys_login_log.ip
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.status
     *
     * @return the value of sys_login_log.status
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.status
     *
     * @param status the value for sys_login_log.status
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_time
     *
     * @return the value of sys_login_log.login_time
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_time
     *
     * @param loginTime the value for sys_login_log.login_time
     *
     * @mbggenerated Wed Aug 07 11:36:21 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}